
<form id="co-shipping_insurance-form" action="">
    <div id="checkout-shipping_insurance-load">
        <?php echo $this->getChildHtml() ?>
    </div>
    <script type="text/javascript">
        //<![CDATA[

        Checkout.steps = ['login', 'billing', 'shipping', 'shipping_method', 'shipping_insurance', 'payment', 'review'];

        var ShippingInsurance = Class.create();
        ShippingInsurance.prototype = {
            initialize: function (form, saveUrl) {
                this.form = form;
                if ($(this.form)) {
                    $(this.form).observe('submit', function (event) {
                        this.save();
                        Event.stop(event);
                    }.bind(this));
                }
                this.saveUrl = saveUrl;
                this.onSave = this.nextStep.bindAsEventListener(this);
                this.onComplete = this.resetLoadWaiting.bindAsEventListener(this);
            },

            save: function () {
                if (checkout.loadWaiting != false) return;

                var validator = new Validation(this.form);
                if (validator.validate()) {

                    checkout.setLoadWaiting('shipping_insurance');


                    var request = new Ajax.Request(
                        this.saveUrl,
                        {
                            method: 'post',
                            onComplete: this.onComplete,
                            onSuccess: this.onSave,
                            onFailure: checkout.ajaxFailure.bind(checkout),
                            parameters: Form.serialize(this.form)
                        }
                    );
                }
            },

            resetLoadWaiting: function (transport) {
                checkout.setLoadWaiting(false);
            },

            nextStep: function(transport){
                if (transport && transport.responseText){
                    try{
                        response = eval('(' + transport.responseText + ')');
                    }
                    catch (e) {
                        response = {};
                    }
                }

                if (response.error) {
                    alert(response.message);
                    return false;
                }

                if (response.update_section) {
                    $('checkout-'+response.update_section.name+'-load').update(response.update_section.html);
                }

                payment.initWhatIsCvvListeners();

                if (response.goto_section) {
                    checkout.gotoSection(response.goto_section);
                    checkout.reloadProgressBlock();
                    return;
                }

                if (response.payment_methods_html) {
                    $('checkout-payment-method-load').update(response.payment_methods_html);
                }

                return;
            }
        }

        var shippingInsurance = new ShippingInsurance('co-shipping_insurance-form', '<?php echo $this->getUrl('insurance/onepage/saveInsurance') ?>');
        //]]>
    </script>

    <div class="buttons-set" id="shipping_insurance-buttons-container">
        <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="button" class="button" onclick="shippingInsurance.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span id="shipping_insurance-please-wait" class="please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>
</form>


